version: '3.3'
services:
  php:
    build: ./tools/docker/php7-fpm
    environment:
        APP_ENV: dev
    volumes:
      - ./:/var/www/application/
      - ./tools/docker/php7-fpm/php.ini:/usr/local/etc/php/conf.d/my.ini:ro
    networks:
      - web  
  nginx:
    build: ./tools/docker/nginx
    volumes:
      - ./:/var/www/application/
      - ./tools/docker/nginx/log:/var/log/nginx  
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.nginx.rule=Host(`www.crm.local.com`)"
      - "traefik.http.services.nginx.loadbalancer.server.port=80"
    ports:
      - 80 
    networks:
      - web
  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD: haikel
      POSTGRES_USER: haikel
      POSTGRES_DB: grafikart
      TZ: Europe/Paris
      PGTZ: Europe/Paris
    ports:
      - 5432:5432 
    volumes:
      - db-data_crm:/var/lib/postgresql/data
    networks:
        - web
  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - ./data:/data
    restart: always
    networks:
      - web    
  redis-gui:
    image: rediscommander/redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"   
    networks:
      - web
  mail:
    image: mailhog/mailhog
    ports:
      - 1090:8025
    volumes:
      - ./volumes/mailhog/volume:/maildir
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.mail.rule=Host(`www.mail.local.com`)"
      - "traefik.http.services.mail.loadbalancer.server.port=1090"
    networks:
      - web
  portainer:
      image: portainer/portainer
      expose:
        - "9000"
      networks:
        - web
      labels:    
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.portainer.rule=Host(`www.portainer.local.com`)"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000" 
      volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
        - portainer-data-crm:/data
  traefik:
    image: traefik:v2.1
    command: 
      - --api.insecure=true 
      - --providers.docker 
      - --providers.docker.exposedByDefault=false 
      - --providers.docker.network=internal
    ports:
      - "80:80"
      - 8080:8080
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  mercure:
    image: dunglas/mercure
    environment:
      JWT_KEY: mercure_subscriber
      PUBLISHER_JWT_KEY: mercure_publisher
      ALLOW_ANONYMOUS: 1
      CORS_ALLOWED_ORIGINS: 'http://www.crm.local.com'
    ports:
      - 8001:80
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.mercure.rule=Host(`www.mercure.local.com`)"
      - "traefik.http.services.mercure.loadbalancer.server.port=8001"
    networks:
      - web
networks:
  web:
    driver: bridge
volumes:
  portainer-data-crm: {}
  db-data_crm: {}
