<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJ15eIBg\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJ15eIBg/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJ15eIBg.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJ15eIBg\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJ15eIBg\App_KernelDevDebugContainer([
    'container.build_hash' => 'J15eIBg',
    'container.build_id' => 'facc77a1',
    'container.build_time' => 1601834114,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJ15eIBg');
